import Link from "next/link";
import shared from "./premier.module.css";
import s from "./services.module.css";

export function AboutStory() {
  return <>
    <section className={s.aboutFilm} aria-labelledby="film-heading"><div><span className={shared.eyebrow}>THE PEOPLE. THE PURPOSE. PREMIER.</span><h2 id="film-heading">A closer look at<br />what drives us.</h2><p>Meet the company behind your next chapter. Watch the Premier film featured on Cory Swain’s welcome page.</p><a href="https://player.vimeo.com/video/681660681?dnt=1" target="_blank" rel="noreferrer">Open the company film ↗</a></div><iframe src="https://player.vimeo.com/video/681660681?dnt=1" title="Premier Mortgage Resources company recruiting film" loading="lazy" allow="fullscreen; picture-in-picture; encrypted-media" allowFullScreen /></section>
    <section className={s.aboutPurpose}><span className={shared.eyebrow}>01 / WHY WE’RE HERE</span><h2>Behind every loan,<br /><span>someone’s life is moving forward.</span></h2><p>First keys. More space. A fresh start. We believe home financing should begin with the person—not just the paperwork. Our role is to help you understand your options and move forward with a team you can talk to.</p></section>
    <section className={s.aboutLeaders} aria-labelledby="about-leaders"><div><span className={shared.eyebrow}>02 / PEOPLE BEHIND THE PURPOSE</span><h2 id="about-leaders">Personal commitment.<br />Shared direction.</h2><p>Cory’s message to customers and employees centers on people, dependable support, and doing the work well. That commitment shapes how we approach every relationship.</p><Link href="/team#leadership" className={shared.secondary}>Meet our leadership ↗</Link></div><div className={s.founderCards}>{[["Cory Swain","Chief Executive Officer","cory-swain-neutral"],["Mandi Feely Swain","Co-Founder","mandi-feely-swain"]].map(([name,title,photo])=><article key={name}><div><img src={`/team/${photo}.png`} alt={name} loading="lazy" /></div><h3>{name}</h3><p>{title}</p></article>)}</div></section>
    <section className={s.aboutHistory}><span className={shared.eyebrow}>03 / OUR STORY</span><h2>Built over time.<br />Looking ahead.</h2><div>{[["2005","A new chapter","PMR’s official relaunch continued its work helping customers become homeowners."],["2021","A home in Idaho","The company relocated its headquarters to Meridian under Cory Swain’s ownership."],["2022","A shared stake","An employee stock ownership plan made employees stakeholders in PMR’s future."]].map(([year,title,body])=><article key={year}><span>{year}</span><h3>{title}</h3><p>{body}</p></article>)}</div></section>
    <section className={s.aboutSteps}><span className={shared.eyebrow}>04 / YOUR PATH WITH PREMIER</span><h2>Big decisions.<br />Human guidance.</h2><div>{[["Start with a conversation","Tell a loan officer where you are and what you’re working toward."],["Understand your options","Talk through financing choices and the details that matter to you."],["Move forward together","Get guidance on documents, next steps, and the path toward closing."]].map(([title,body],i)=><article key={title}><span>0{i+1}</span><h3>{title}</h3><p>{body}</p></article>)}</div></section>
    <aside className={s.support}><div><h2>Your next chapter starts with people.</h2><p>Looking for a home loan—or a place to build your career?</p></div><div className={s.aboutLinks}><Link href="/find-a-loan-officer" className={shared.primary}>Find your loan officer ↗</Link><Link href="/careers" className={shared.secondary}>Explore careers ↗</Link></div></aside>
  </>;
}
