import Link from "next/link";
import type { ReactNode } from "react";
import { PremierHeader, PremierFooter, Arrow } from "./PremierSite";
import shared from "./premier.module.css";
import s from "./services.module.css";
import { StateLicenses } from "./StateLicenses";
import { JoinExtras } from "./JoinExtras";
import { AboutStory } from "./AboutStory";

function Action({ href, children, secondary = false }: { href: string; children: ReactNode; secondary?: boolean }) {
  return <a href={href} className={secondary ? shared.secondary : shared.primary}>{children}<Arrow diagonal={href.startsWith("https:")} /></a>;
}
function Frame({ label, title, accent, intro, children }: { label: string; title: string; accent: string; intro: string; children: ReactNode }) {
  const recruiting = label === "Careers" || label === "Join PMR";
  return <div className={shared.page}><PremierHeader /><main id="main" className={`${s.main} ${recruiting ? s.recruiting : ""}`}><div className={s.breadcrumb}><Link href="/">Home</Link><span>/</span><span>{label}</span></div><header className={`${s.hero} ${recruiting ? s.recruitHero : ""}`}><span className={shared.eyebrow}>{label.toUpperCase()}</span><h1>{recruiting ? "Build your future." : title}<br /><span>{recruiting ? "Help shape theirs." : accent}</span></h1><p>{intro}</p>{recruiting && <div className={s.recruitActions}><Action href="#roles">Explore open positions</Action><Link href="/team">Meet the people behind Premier <Arrow /></Link></div>}</header>{recruiting && <nav className={s.recruitNav} aria-label="Explore careers"><Link href="/join-pmr">/01 <span>Life at Premier</span></Link><Link href="/join-pmr#coverage">/02 <span>Our reach</span></Link><Link href="/join-pmr#testimonials">/03 <span>Our people</span></Link><a href="#roles">/04 <span>Open positions</span></a></nav>}{children}</main><PremierFooter /></div>;
}
function Support() {
  return <aside className={s.support}><div><span className={shared.eyebrow}>A REAL PERSON. A LITTLE CLARITY.</span><h2>Not sure where to start?</h2><p>Our servicing team can help you find the right payment option.</p></div><Action href="tel:+18667334782" secondary>Call (866) 733-4782</Action></aside>;
}
export function PaymentPage() {
  return <Frame label="Make a payment" title="Your home. Your payment." accent="One clear next step." intro="Choose the option that matches your loan. Have your latest mortgage statement handy to confirm your servicer."><div className={s.twoCards}><article className={`${s.card} ${s.dark}`}><span className={s.index}>01 / SERVBANK CUSTOMERS</span><h2>Everything you need.<br />In your borrower portal.</h2><p>If Servbank services your loan, sign in to manage your account and make your payment.</p><div className={s.actions}><Action href="https://myloan.servbank.com/Account/Login">Log in to Servbank</Action><a href="https://myloan.servbank.com/Account/Register" className={s.textLink}>New here? Register your account <Arrow diagonal /></a></div><span className={s.note}>Continues to Servbank’s secure website.</span></article><article className={s.card}><span className={s.index}>02 / OTHER PMR PAYMENTS</span><h2>A one-time payment.<br />A simple way forward.</h2><p>For other payments directed to PMR, continue to the REPAY portal. Confirm the payment instructions on your statement first.</p><div className={s.actions}><Action href="https://pmrloans.repay.io/portal/guest-account-lookup">Make a one-time payment</Action></div><span className={s.note}>Continues to PMR’s secure REPAY portal.</span></article></div><Support /><div className={s.faq}><h2>A little help before you pay.</h2><details><summary>Where do I find my servicer?</summary><p>Check the company name and payment instructions on your most recent mortgage statement. If you are unsure, call our servicing team before making a payment.</p></details><details><summary>Will I enter payment details on this page?</summary><p>No. Your account login and payment details are entered only on the secure payment provider’s website.</p></details></div></Frame>;
}
export function AboutPage() {
  return <Frame label="About Premier" title="Home is the reason." accent="People are the difference." intro="We’re Premier Mortgage Resources. A team of people helping you make room for what comes next."><AboutStory /></Frame>;
}
const jobs = [
  ["Chief Operating Officer", "Executive leadership", "Lead operational strategy, credit risk, and the teams moving loans forward.", "733"],
  ["General Counsel", "Legal", "Guide the company’s legal strategy and advise leadership on risk and business decisions.", "744"],
  ["Licensing Manager", "Compliance", "Oversee company, branch, and loan-officer licensing operations.", "742"],
  ["Vendor Management Specialist", "Remote · Full-time", "Support third-party oversight, regulatory compliance, and vendor risk management.", "646"],
  ["Loan Officer", "Production", "Help clients navigate home financing with the support of the Premier team.", "715"],
];
export function CareersPage() {
  return <Frame label="Careers" title="Good people. Great work." accent="Find your place at Premier." intro="Explore opportunities across production, operations, and leadership. Your next chapter could start here."><aside className={s.support}><div><span className={shared.eyebrow}>FOR LOAN OFFICERS</span><h2>Your business. Your next chapter.</h2><p>Explore the people, tools, and support behind a career at Premier.</p></div><Action href="/loan-officer-careers">Loan officer careers</Action></aside><section id="roles" aria-labelledby="careers-heading"><span className={shared.eyebrow}>CURRENT OPPORTUNITIES</span><h2 id="careers-heading" className={s.careersHeading}>A role for what you do best.</h2><p className={s.note}>Listed on PMR’s careers page, reviewed September 9, 2026. See each application for current availability and full requirements.</p>{jobs.map(([title,tag,body,id])=><article className={s.job} key={id}><div><span className={s.index}>{tag}</span><h3>{title}</h3><p>{body}</p></div><Action href={`https://jobs.dayforcehcm.com/en-US/pmrloans/CANDIDATEPORTAL/jobs/${id}`} secondary>View role & apply</Action></article>)}</section><aside className={s.support}><div><span className={shared.eyebrow}>LET’S MEET</span><h2>Don’t see your role?</h2><p>Share your experience through our general application.</p></div><Action href="https://jobs.dayforcehcm.com/en-US/pmrloans/CANDIDATEPORTAL/jobs/672">General application</Action></aside><div className={s.support}><div><h2>Get to know your next team.</h2><p>Learn about the people and purpose behind Premier.</p></div><Action href="/join-pmr" secondary>Life at Premier</Action></div></Frame>;
}
export function JoinPage() {
  return <Frame label="Join PMR" title="Your next chapter." accent="Our next teammate." intro="Bring your ambition. Bring your perspective. Build a mortgage career with people who care about your progress."><div className={s.careerIntro}><div><span className={shared.eyebrow}>GROW WITH PREMIER</span><h2>Good support changes<br />what’s possible.</h2><p>Technology, operations, and marketing work together to support our mortgage professionals. Spend more time building relationships, with people behind you to help move the work forward.</p><Action href="#roles">Explore open roles</Action></div><div className={s.pillars}>{[["01", "Tools that work with you", "Technology to support your day-to-day workflow."], ["02", "People in your corner", "Operations and marketing support for your business."], ["03", "A shared future", "An employee-ownership culture, built together."]].map(([n,t,d])=><div key={n}><span>{n}</span><div><h3>{t}</h3><p>{d}</p></div></div>)}</div></div><JoinExtras /><section className={s.roles} id="roles"><span className={shared.eyebrow}>FIND YOUR PLACE</span><h2>Make your next move.</h2><p>Positions listed by PMR. The application portal has current availability and complete requirements.</p>{jobs.map(([title,tag,body,id])=><article className={s.job} key={id}><div><span className={s.index}>{tag}</span><h3>{title}</h3><p>{body}</p></div><Action href={`https://jobs.dayforcehcm.com/en-US/pmrloans/CANDIDATEPORTAL/jobs/${id}`} secondary>View role & apply</Action></article>)}</section><aside className={s.support}><div><h2>A talent we haven’t listed?</h2><p>Tell us where you’d like to make a difference.</p></div><Action href="https://jobs.dayforcehcm.com/en-US/pmrloans/CANDIDATEPORTAL/jobs/672">General application</Action></aside></Frame>;
}
export function ContactPage() {
  return <Frame label="Contact us" title="Questions welcome." accent="People ready to help." intro="Whether you’re planning your next move or looking for help with an existing loan, let’s get you to the right team."><div className={s.threeCards}><article className={s.card}><span className={s.index}>01 / HOME FINANCING</span><h2>Start a conversation.</h2><p>Find a loan officer to talk through buying, refinancing, or your next home.</p><Action href="/find-a-loan-officer">Find your person</Action></article><article className={`${s.card} ${s.dark}`}><span className={s.index}>02 / EXISTING LOANS</span><h2>Get payment help.</h2><p>Questions about a payment or where to find your loan account?</p><Action href="tel:+18667334782">(866) 733-4782</Action><a className={s.textLink} href="/make-a-payment">Payment options <Arrow /></a></article><article className={s.card}><span className={s.index}>03 / GENERAL QUESTIONS</span><h2>Talk to Premier.</h2><p>Our main office can help direct your question to the right person.</p><Action href="tel:+12086290606">(208) 629-0606</Action></article></div><div className={s.office}><div><span className={shared.eyebrow}>OUR HOME BASE</span><h2>Meridian, Idaho.</h2><address>Premier Mortgage Resources, LLC<br />3363 E. Presidential Dr #200<br />Meridian, ID 83642</address></div><div><h3>Keep sensitive information secure.</h3><p>Please don’t send account numbers, Social Security numbers, or financial documents through general messages. Your loan officer can direct you to the appropriate secure channel.</p><p>Fax: (888) 678-7090</p></div></div></Frame>;
}
const compliance = {
  "privacy-policy": {label:"Privacy policy", title:"Your information.", accent:"Your peace of mind.", intro:"Understand how Premier handles personal information and where to find the complete policy.", sections:[["Information and its use", "Premier’s policy describes personal, financial, transaction, device, and usage information collected to provide mortgage services, manage accounts, communicate with customers, and meet legal obligations."],["Choices and controls", "The policy covers cookies, marketing opt-outs, third-party services, retention, security, and disclosures. It states that mobile information and text-message consent are not shared for third-party marketing."],["Read the complete policy", "This overview is not a replacement for the full privacy policy, last updated September 5, 2025. Review the official document for all definitions, details, and contact information."]]},
  "legal": {label:"Legal", title:"Clear information.", accent:"Important details.", intro:"A place to find the terms that apply to Premier’s website and mortgage information.", sections:[["Information, not an offer", "Website content provides general information and does not constitute a mortgage offer or professional tax, legal, or financial advice. Seek advice appropriate to your circumstances before acting."],["Availability and changes", "Products and services vary by location and individual circumstances. Information may change without notice, and completeness, accuracy, and timeliness are not guaranteed."],["Website use", "Premier’s official disclaimer addresses permitted use, intellectual property, limitations of liability, and other conditions. This overview does not replace those terms."]]},
  "state-licensing": {label:"State licensing", title:"Local knowledge.", accent:"Licensed expertise.", intro:"Premier Mortgage Resources, LLC · NMLS #1169. Verify licensing and program availability before beginning your loan.", sections:[["Verify a license", "Use NMLS Consumer Access to review company and individual licensing records. A loan officer can help confirm whether a product is available for your property and circumstances."],["State-specific details", "Premier maintains a state-by-state list of licenses, registration numbers, and required disclosures, including the Texas complaint and recovery-fund notice."],["Availability matters", "Loan products and amounts depend on location, credit and property approval, and agency or investor requirements. Some programs are provided through lending partners; additional restrictions may apply."]]}
};
export type ComplianceSlug = keyof typeof compliance;
export function CompliancePage({slug}: {slug:ComplianceSlug}) {
  const page=compliance[slug];
  if (slug === "state-licensing") return <Frame label={page.label} title={page.title} accent={page.accent} intro={page.intro}><StateLicenses /></Frame>;
  return <Frame label={page.label} title={page.title} accent={page.accent} intro={page.intro}><div className={s.documentLayout}><nav className={s.documentNav} aria-label="Compliance pages"><span className={shared.eyebrow}>GOOD TO KNOW</span>{Object.entries(compliance).map(([key,value])=><Link href={`/${key}`} key={key} aria-current={slug===key?"page":undefined}>{value.label}<Arrow /></Link>)}</nav><article className={s.document}>{page.sections.map(([title,body],i)=><section key={title}><span className={s.index}>0{i+1}</span><h2>{title}</h2><p>{body}</p></section>)}<div className={s.documentActions}><Action href={`https://www.pmrloans.com/${slug}/`}>Read official {page.label.toLowerCase()}</Action><p className={s.note}>The linked official document remains the source of record. Reviewed September 9, 2026.</p></div></article></div></Frame>;
}
