import s from "./services.module.css";

// License facts from https://www.pmrloans.com/state-licensing/, reviewed 2026-09-09.
export const licenses = [
  ["Alabama", "22968", "Consumer Credit License"],
  ["Alaska", "AK1169; AK 1169-1; AK 1169-2", "Mortgage Broker / Lender License; Other Trade Names #1 and #2"],
  ["Arizona", "AZ BK 0937529", "Mortgage Banker License"],
  ["Arkansas", "129142", "Combination Mortgage Banker-Broker-Servicer License. Doing business as PMRLOANS, LLC."],
  ["California", "4131279", "DFPI Residential Mortgage Lending Act License. Licensed by the Department of Financial Protection and Innovation under the California Residential Mortgage Lending Act."],
  ["Colorado", "1169", "Mortgage Company Registration"],
  ["Connecticut", "ML-1169", "Mortgage Lender License"],
  ["Delaware", "037811", "Lender License; licensed by the Delaware State Bank Commissioner to engage in business in Delaware."],
  ["Florida", "MLD2088", "Mortgage Lender Servicer License"],
  ["Georgia", "1169", "Mortgage Lender License / Registration"],
  ["Hawaii", "Hi-1169 HI", "Mortgage Loan Originating Company License"],
  ["Idaho", "MBL-8434", "Mortgage Broker / Lender License"],
  ["Illinois", "MB.6761622", "Residential Mortgage License — Correspondent only"],
  ["Indiana", "62724", "Indiana-DFI Mortgage Lending License"],
  ["Iowa", "2022-0130", "Mortgage Banker License"],
  ["Kansas", "MC.0025252", "Mortgage Company License"],
  ["Kentucky", "MC.823047", "Mortgage Company License"],
  ["Louisiana", "1169", "Residential Mortgage Lending License"],
  ["Maine", "1169", "Supervised Lender License"],
  ["Maryland", "1169", "Mortgage Lender License"],
  ["Massachusetts", "ML-1169", "Mortgage Lender License"],
  ["Michigan", "FR0024297; SR0024298", "Mortgage Broker, Mortgage Lender, and Mortgage Servicer Licenses"],
  ["Minnesota", "MN-MO-1169; MN-MS-1169", "Residential Mortgage Originator and Residential Mortgage Servicer Licenses"],
  ["Mississippi", "1169", "Mortgage Lender License"],
  ["Missouri", "1169", "Mortgage Company License"],
  ["Montana", "1169", "Mortgage Broker, Mortgage Lender, and Mortgage Servicer Licenses"],
  ["Nebraska", "1169", "Mortgage Banker License. Doing business as PMRLOANS, LLC."],
  ["Nevada", "4639", "Mortgage Company License"],
  ["New Hampshire", "26389-MB", "Mortgage Company License"],
  ["New Jersey", "1169", "NJ RMLA-Licensed Mortgage Servicer Registration"],
  ["New Mexico", "1169", "Mortgage Loan Company License"],
  ["New York", "Not listed", "No New York license is listed on PMR’s published licensing page. Contact PMR to confirm availability."],
  ["North Carolina", "L-206465", "Mortgage Lender License"],
  ["North Dakota", "MB103957", "Money Broker License"],
  ["Ohio", "RM.805078.000", "Residential Mortgage Lending Act Certificate of Registration"],
  ["Oklahoma", "ML014603", "Mortgage Lender License"],
  ["Oregon", "ML-3709; MS-190", "Mortgage Lending and Mortgage Servicer Licenses"],
  ["Pennsylvania", "97707 (lender); 97708 (servicer)", "Mortgage Lender and Mortgage Servicer Licenses"],
  ["Rhode Island", "20234604LB", "Loan Broker License"],
  ["South Carolina", "MLS – 1169", "BFI Mortgage Lender / Servicer License"],
  ["South Dakota", "1169.ML", "Mortgage Lender License"],
  ["Tennessee", "219243", "Mortgage License"],
  ["Texas", "1169", "SML Mortgage Banker Registration"],
  ["Utah-DRE", "13877076", "Mortgage Entity License — Other trade name #1"],
  ["Vermont", "LS-1169; LL-1169; MB-1169", "Loan Servicer, Loan Lender, and Mortgage Broker Licenses"],
  ["Virginia", "MC-7459", "Mortgage Lender License"],
  ["Washington", "CL-1169", "Consumer Loan Company License"],
  ["Washington, DC", "MLB1169", "District of Columbia Mortgage Banker and Mortgage Broker Licenses"],
  ["West Virginia", "MB-1169; ML-1169", "Mortgage Broker and Mortgage Lender Licenses"],
  ["Wisconsin", "1169BA; 1169BR", "Mortgage Banker License"],
  ["Wyoming", "4319", "Mortgage Broker / Lender License"],
];

export function StateLicenses() {
  return <section className={s.licenseSection} aria-labelledby="license-heading"><h2 id="license-heading">State-by-state licensing</h2><p>Premier Mortgage Resources, LLC · NMLS #1169</p><div className={s.licenseTableWrap} tabIndex={0} role="region" aria-label="State licenses table"><table className={s.licenseTable}><caption>Published licenses for 49 states and Washington, DC. New York is marked as not listed. Reviewed September 9, 2026.</caption><thead><tr><th scope="col">State</th><th scope="col">License / registration</th><th scope="col">Type and disclosures</th></tr></thead><tbody>{licenses.map(([state,number,type])=><tr key={state}><th scope="row">{state}</th><td>{number}</td><td>{type}</td></tr>)}</tbody></table></div><p className={s.note}>Source: <a href="https://www.pmrloans.com/state-licensing/">PMR’s published state licensing list</a>. Confirm current records through <a href="https://www.nmlsconsumeraccess.org/">NMLS Consumer Access</a>.</p><h2>Texas complaint and recovery fund</h2><p>Texas consumers can obtain complaint forms, filing instructions, and recovery-fund information from the <a href="https://www.sml.texas.gov/">Texas Department of Savings and Mortgage Lending</a>, or call <a href="tel:+18772765550">1-877-276-5550</a>. Review the complete Texas notice on <a href="https://www.pmrloans.com/state-licensing/">PMR’s official licensing page</a>.</p></section>;
}
